=== mxjoly/pwa-webpack-plugin/lib/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["favicons"],
  "additionalProperties": false,
  "properties": {
    "favicons": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[A-Za-z0-9-_]+\\.png$": {
          "type": "object",
          "required": [
            "width",
            "height",
            "rel",
            "type",
            "transparent",
            "mask",
            "shadow",
            "emitTag"
          ],
          "additionalProperties": false,
          "properties": {
            "width": {
              "type": "number",
              "enum": [16, 32, 48, 96]
            },
            "height": {
              "type": "number",
              "enum": [16, 32, 48, 96]
            },
            "rel": {
              "type": "string",
              "enum": ["icon"]
            },
            "type": {
              "type": "string",
              "enum": ["image/png"]
            },
            "transparent": {
              "type": "boolean"
            },
            "mask": {
              "type": "boolean"
            },
            "shadow": {
              "type": "boolean"
            },
            "emitTag": {
              "type": "boolean"
            }
          }
        }
      }
    },
    "android": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[A-Za-z0-9-_]+\\.png$": {
          "type": "object",
          "required": [
            "width",
            "height",
            "rel",
            "type",
            "transparent",
            "mask",
            "shadow",
            "emitTag"
          ],
          "additionalProperties": false,
          "properties": {
            "width": {
              "type": "number",
              "enum": [128, 192, 196, 256, 512]
            },
            "height": {
              "type": "number",
              "enum": [128, 192, 196, 256, 512]
            },
            "rel": {
              "type": "string",
              "enum": ["icon"]
            },
            "type": {
              "type": "string",
              "enum": ["image/png"]
            },
            "transparent": {
              "type": "boolean"
            },
            "mask": {
              "type": "boolean"
            },
            "shadow": {
              "type": "boolean"
            },
            "emitTag": {
              "type": "boolean"
            }
          }
        }
      }
    },
    "apple": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[A-Za-z0-9-_]+\\.png$": {
          "type": "object",
          "required": [
            "width",
            "height",
            "rel",
            "type",
            "transparent",
            "mask",
            "shadow",
            "emitTag"
          ],
          "additionalProperties": false,
          "properties": {
            "width": {
              "type": "number",
              "enum": [128, 152, 167, 180]
            },
            "height": {
              "type": "number",
              "enum": [128, 152, 167, 180]
            },
            "rel": {
              "type": "string",
              "enum": ["apple-touch-icon"]
            },
            "type": {
              "type": "string",
              "enum": ["image/png"]
            },
            "transparent": {
              "type": "boolean"
            },
            "mask": {
              "type": "boolean"
            },
            "shadow": {
              "type": "boolean"
            },
            "emitTag": {
              "type": "boolean"
            }
          }
        }
      }
    },
    "appleStartup": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[A-Za-z0-9-_]+\\.png$": {
          "type": "object",
          "required": [
            "dwidth",
            "dheight",
            "ratio",
            "rel",
            "type",
            "transparent",
            "mask",
            "shadow",
            "emitTag"
          ],
          "additionalProperties": false,
          "properties": {
            "dwidth": {
              "type": "number"
            },
            "dheight": {
              "type": "number"
            },
            "ratio": {
              "type": "number",
              "enum": [1, 2, 3]
            },
            "rel": {
              "type": "string",
              "enum": ["apple-touch-startup-image"]
            },
            "type": {
              "type": "string",
              "enum": ["image/png"]
            },
            "transparent": {
              "type": "boolean"
            },
            "mask": {
              "type": "boolean"
            },
            "shadow": {
              "type": "boolean"
            },
            "emitTag": {
              "type": "boolean"
            }
          }
        }
      }
    },
    "windows": {
      "type": "object",
      "required": ["mstile-70x70.png"],
      "additionalProperties": false,
      "properties": {
        "mstile-70x70.png": {
          "type": "object",
          "required": [
            "width",
            "height",
            "rel",
            "type",
            "transparent",
            "mask",
            "shadow",
            "emitTag"
          ],
          "additionalProperties": false,
          "properties": {
            "width": {
              "type": "number",
              "enum": [70]
            },
            "height": {
              "type": "number",
              "enum": [70]
            },
            "rel": {
              "type": "string",
              "enum": ["icon"]
            },
            "type": {
              "type": "string",
              "enum": ["image/png"]
            },
            "transparent": {
              "type": "boolean"
            },
            "mask": {
              "type": "boolean"
            },
            "shadow": {
              "type": "boolean"
            },
            "emitTag": {
              "type": "boolean"
            }
          }
        },
        "mstile-270x270.png": {
          "type": "object",
          "required": [
            "width",
            "height",
            "rel",
            "type",
            "transparent",
            "mask",
            "shadow",
            "emitTag"
          ],
          "additionalProperties": false,
          "properties": {
            "width": {
              "type": "number",
              "enum": [270]
            },
            "height": {
              "type": "number",
              "enum": [270]
            },
            "rel": {
              "type": "string",
              "enum": ["icon"]
            },
            "type": {
              "type": "string",
              "enum": ["image/png"]
            },
            "transparent": {
              "type": "boolean"
            },
            "mask": {
              "type": "boolean"
            },
            "shadow": {
              "type": "boolean"
            },
            "emitTag": {
              "type": "boolean"
            }
          }
        },
        "mstile-310x310.png": {
          "type": "object",
          "required": [
            "width",
            "height",
            "rel",
            "type",
            "transparent",
            "mask",
            "shadow",
            "emitTag"
          ],
          "additionalProperties": false,
          "properties": {
            "width": {
              "type": "number",
              "enum": [310]
            },
            "height": {
              "type": "number",
              "enum": [310]
            },
            "rel": {
              "type": "string",
              "enum": ["icon"]
            },
            "type": {
              "type": "string",
              "enum": ["image/png"]
            },
            "transparent": {
              "type": "boolean"
            },
            "mask": {
              "type": "boolean"
            },
            "shadow": {
              "type": "boolean"
            },
            "emitTag": {
              "type": "boolean"
            }
          }
        },
        "mstile-310x150.png": {
          "type": "object",
          "required": [
            "width",
            "height",
            "rel",
            "type",
            "transparent",
            "mask",
            "shadow",
            "emitTag"
          ],
          "additionalProperties": false,
          "properties": {
            "width": {
              "type": "number",
              "enum": [310]
            },
            "height": {
              "type": "number",
              "enum": [150]
            },
            "rel": {
              "type": "string",
              "enum": ["icon"]
            },
            "type": {
              "type": "string",
              "enum": ["image/png"]
            },
            "transparent": {
              "type": "boolean"
            },
            "mask": {
              "type": "boolean"
            },
            "shadow": {
              "type": "boolean"
            },
            "emitTag": {
              "type": "boolean"
            }
          }
        }
      }
    },
    "safari": {
      "type": "object",
      "additionalProperties": false,
      "required": ["safari-pinned-tab.svg"],
      "properties": {
        "safari-pinned-tab.svg": {
          "type": "object",
          "additionalProperties": false,
          "required": ["width", "height", "rel", "type", "emitTag"],
          "properties": {
            "color": {
              "type": "string",
              "pattern": "^#([0-9abcdef]{3}|[0-9abcdef]{6})$"
            },
            "width": {
              "type": "number",
              "enum": [16]
            },
            "height": {
              "type": "number",
              "enum": [16]
            },
            "rel": {
              "type": "string",
              "enum": ["mask-icon"]
            },
            "type": {
              "type": "string",
              "enum": ["image/svg+xml"]
            },
            "emitTag": {
              "type": "boolean"
            }
          }
        }
      }
    },
    "coast": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[A-Za-z0-9-_]+\\.png$": {
          "type": "object",
          "required": [
            "width",
            "height",
            "rel",
            "type",
            "transparent",
            "mask",
            "shadow",
            "emitTag"
          ],
          "additionalProperties": false,
          "properties": {
            "width": {
              "type": "number",
              "enum": [228]
            },
            "height": {
              "type": "number",
              "enum": [228]
            },
            "rel": {
              "type": "string",
              "enum": ["icon"]
            },
            "type": {
              "type": "string",
              "enum": ["image/png"]
            },
            "transparent": {
              "type": "boolean"
            },
            "mask": {
              "type": "boolean"
            },
            "shadow": {
              "type": "boolean"
            },
            "emitTag": {
              "type": "boolean"
            }
          }
        }
      }
    }
  }
}

=== mxjoly/pwa-webpack-plugin/lib/icons.json
{
  "favicons": {
    "favicon-16x16.png": {
      "width": 16,
      "height": 16,
      "rel": "icon",
      "type": "image/png",
      "transparent": true,
      "mask": false,
      "shadow": false,
      "emitTag": true
    },
    "favicon-32x32.png": {
      "width": 32,
      "height": 32,
      "rel": "icon",
      "type": "image/png",
      "transparent": true,
      "mask": false,
      "shadow": false,
      "emitTag": true
    },
    "favicon-48x48.png": {
      "width": 48,
      "height": 48,
      "rel": "icon",
      "type": "image/png",
      "transparent": true,
      "mask": false,
      "shadow": false,
      "emitTag": true
    },
    "favicon-96x96.png": {
      "width": 96,
      "height": 96,
      "rel": "icon",
      "type": "image/png",
      "transparent": true,
      "mask": false,
      "shadow": false,
      "emitTag": true
    }
  },
  "android": {
    "android-chrome-128x128.png": {
      "width": 128,
      "height": 128,
      "rel": "icon",
      "type": "image/png",
      "transparent": true,
      "mask": false,
      "shadow": false,
      "emitTag": false
    },
    "android-chrome-128x128-maskable.png": {
      "width": 128,
      "height": 128,
      "rel": "icon",
      "type": "image/png",
      "transparent": true,
      "mask": true,
      "shadow": false,
      "emitTag": false
    },
    "android-chrome-192x192.png": {
      "width": 192,
      "height": 192,
      "rel": "icon",
      "type": "image/png",
      "transparent": true,
      "mask": false,
      "shadow": false,
      "emitTag": false
    },
    "android-chrome-192x192-maskable.png": {
      "width": 192,
      "height": 192,
      "rel": "icon",
      "type": "image/png",
      "transparent": true,
      "mask": true,
      "shadow": false,
      "emitTag": false
    },
    "android-chrome-512x512.png": {
      "width": 512,
      "height": 512,
      "rel": "icon",
      "type": "image/png",
      "transparent": true,
      "mask": false,
      "shadow": false,
      "emitTag": false
    },
    "android-chrome-512x512-maskable.png": {
      "width": 512,
      "height": 512,
      "rel": "icon",
      "type": "image/png",
      "transparent": true,
      "mask": true,
      "shadow": false,
      "emitTag": false
    }
  },
  "apple": {
    "apple-touch-icon.png": {
      "width": 180,
      "height": 180,
      "rel": "apple-touch-icon",
      "type": "image/png",
      "transparent": true,
      "mask": false,
      "shadow": false,
      "emitTag": true
    }
  },
  "appleStartup": {
    "iphone5-splash.png": {
      "dwidth": 320,
      "dheight": 568,
      "ratio": 2,
      "rel": "apple-touch-startup-image",
      "type": "image/png",
      "transparent": false,
      "mask": false,
      "shadow": false,
      "emitTag": true
    },
    "iphone6-splash.png": {
      "dwidth": 375,
      "dheight": 667,
      "ratio": 2,
      "rel": "apple-touch-startup-image",
      "type": "image/png",
      "transparent": false,
      "mask": false,
      "shadow": false,
      "emitTag": true
    },
    "iphoneplus-splash.png": {
      "dwidth": 621,
      "dheight": 1104,
      "ratio": 3,
      "rel": "apple-touch-startup-image",
      "type": "image/png",
      "transparent": false,
      "mask": false,
      "shadow": false,
      "emitTag": true
    },
    "iphonex-splash.png": {
      "dwidth": 375,
      "dheight": 812,
      "ratio": 3,
      "rel": "apple-touch-startup-image",
      "type": "image/png",
      "transparent": false,
      "mask": false,
      "shadow": false,
      "emitTag": true
    },
    "iphonexr-splash.png": {
      "dwidth": 414,
      "dheight": 896,
      "ratio": 2,
      "rel": "apple-touch-startup-image",
      "type": "image/png",
      "transparent": false,
      "mask": false,
      "shadow": false,
      "emitTag": true
    },
    "iphonexsmax-splash.png": {
      "dwidth": 414,
      "dheight": 896,
      "ratio": 3,
      "rel": "apple-touch-startup-image",
      "type": "image/png",
      "transparent": false,
      "mask": false,
      "shadow": false,
      "emitTag": true
    },
    "ipad-splash.png": {
      "dwidth": 768,
      "dheight": 1024,
      "ratio": 2,
      "rel": "apple-touch-startup-image",
      "type": "image/png",
      "transparent": false,
      "mask": false,
      "shadow": false,
      "emitTag": true
    },
    "ipadpro1-splash.png": {
      "dwidth": 834,
      "dheight": 1112,
      "ratio": 2,
      "rel": "apple-touch-startup-image",
      "type": "image/png",
      "transparent": false,
      "mask": false,
      "shadow": false,
      "emitTag": true
    },
    "ipadpro2-splash.png": {
      "dwidth": 834,
      "dheight": 1194,
      "ratio": 2,
      "rel": "apple-touch-startup-image",
      "type": "image/png",
      "transparent": false,
      "mask": false,
      "shadow": false,
      "emitTag": true
    },
    "ipadpro3-splash.png": {
      "dwidth": 1024,
      "dheight": 1366,
      "ratio": 2,
      "rel": "apple-touch-startup-image",
      "type": "image/png",
      "transparent": false,
      "mask": false,
      "shadow": false,
      "emitTag": true
    }
  },
  "windows": {
    "mstile-70x70.png": {
      "width": 70,
      "height": 70,
      "rel": "icon",
      "type": "image/png",
      "transparent": false,
      "mask": false,
      "shadow": false,
      "emitTag": false
    },
    "mstile-270x270.png": {
      "width": 270,
      "height": 270,
      "rel": "icon",
      "type": "image/png",
      "transparent": false,
      "mask": false,
      "shadow": false,
      "emitTag": false
    },
    "mstile-310x310.png": {
      "width": 310,
      "height": 310,
      "rel": "icon",
      "type": "image/png",
      "transparent": false,
      "mask": false,
      "shadow": false,
      "emitTag": false
    },
    "mstile-310x150.png": {
      "width": 310,
      "height": 150,
      "rel": "icon",
      "type": "image/png",
      "transparent": false,
      "mask": false,
      "shadow": false,
      "emitTag": false
    }
  },
  "safari": {
    "safari-pinned-tab.svg": {
      "color": "#000",
      "width": 16,
      "height": 16,
      "rel": "mask-icon",
      "type": "image/svg+xml",
      "emitTag": true
    }
  },
  "coast": {
    "coast-228x228.png": {
      "width": 228,
      "height": 228,
      "rel": "icon",
      "type": "image/png",
      "transparent": false,
      "mask": false,
      "shadow": false,
      "emitTag": true
    }
  }
}
